project_id = "cccktfactlzxuprpyhgh"

[functions.create-esim]
verify_jwt = false

[functions.test-esim]
verify_jwt = false

[functions.debug-simple]
verify_jwt = false

[functions.get-admin-inventory]
verify_jwt = false

[functions.get-admin-users]
verify_jwt = false

[functions.get-esim-details]
verify_jwt = false

[functions.esim-webhook]
verify_jwt = false

[functions.sync-maya-plans]
verify_jwt = false

[functions.create-maya-esim]
verify_jwt = false

[functions.process-maya-topup]
verify_jwt = false

[functions.get-maya-esim-status]
verify_jwt = false

[functions.get-maya-topup-plans]
verify_jwt = false