project_id = "cccktfactlzxuprpyhgh"

[functions.create-esim]
verify_jwt = true

[functions.test-esim]
verify_jwt = false

[functions.debug-simple]
verify_jwt = false

[functions.get-admin-inventory]
verify_jwt = true

[functions.get-admin-users]
verify_jwt = true

[functions.get-esim-details]
verify_jwt = true

[functions.esim-webhook]
verify_jwt = false

[functions.sync-maya-plans]
verify_jwt = false

[functions.create-maya-esim]
verify_jwt = true

[functions.process-maya-topup]
verify_jwt = true

[functions.get-maya-esim-status]
verify_jwt = true

[functions.get-maya-topup-plans]
verify_jwt = true

[functions.create-topup]
verify_jwt = true

[functions.sync-topups]
verify_jwt = true

[functions.confirm-topup]
verify_jwt = true

[functions.get-topup-plans]
verify_jwt = true

[functions.realtime-maya-sync]
verify_jwt = false

[functions.sync-esim-plans]
verify_jwt = false

[functions.wallet-debit]
verify_jwt = true

[functions.setup-algolia-sync]
verify_jwt = true

[functions.get-algolia-credentials]
verify_jwt = true

[functions.sync-algolia-realtime]
verify_jwt = true

[functions.export-plan-uuids]
verify_jwt = true

[functions.get-agent-plan-prices]
verify_jwt = true

[functions.system-health-check]
verify_jwt = true

[functions.ai-plan-assistant]
verify_jwt = true