project_id = "cccktfactlzxuprpyhgh"

[functions.create-esim]
verify_jwt = false

[functions.test-esim]
verify_jwt = false

[functions.debug-simple]
verify_jwt = false

[functions.get-admin-inventory]
verify_jwt = false