// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovvyffsncateldlxlsba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92dnlmZnNuY2F0ZWxkbHhsc2JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzNzExOTksImV4cCI6MjA3Njk0NzE5OX0.ELl3EkprLscA1qhgHR4mBnkYSfnNHrj9UZqL2rPOgwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

export const __SUPABASE_URL__ = SUPABASE_URL;